---
title: "Does Not Playing Hockey Make You Worse at Hockey? Project Progress 7-21-22"
author: "Jackie Jovanovic, Michele Sezgin"
output: 
  html_document:
    code_folding: hide
date: 'July 21st, 2022'
---

```{r load-packages, include = FALSE}
# load the packages
library(tidyverse)
library(patchwork)
library(lubridate)
library(ggridges)
library(RColorBrewer)
library(kableExtra)
```

### Purpose

Project Motivation: Investigate the impact of pandemic restrictions on hockey player development.

*   In 2020-2021 many junior/NHL-feeder leagues had a shortened season or no season
*   Players had to find new leagues and/or tournament
*   Some players did not play that season

### Data

```{r data}
ohl <- read_csv("../../sams_ohl_data_request.csv")
ohl_covid <- ohl %>%
  filter(season %in% c("2019-2020","2020-2021", "2021-2022"))
```

```{r}
## Add treatment var:

# Filtering only for players who played more than 10 games (should we combine number of games played across leagues?)
# ohl_20_21 <- ohl %>%
#   filter(season == "2020-2021", gp > 10)
# 
# # Split players up into treatment vs non-treatment
# ohl_treatment <- ohl %>%
#   filter(season %in% c("2019-2020", "2021-2022"), league == "OHL") %>%
#   group_by(player_id, season) %>%
#   mutate(ppg = sum(pts)/sum(gp),
#          treatment = ifelse(player_id %in% ohl_20_21$player_id, "Played", "Didn't play")
#   ) %>%
#   ungroup()

# Create df of players who played during covid w total gp and if they played championship
ohl_treatment_prep <- ohl %>%
  filter(season == "2020-2021") %>%
  group_by(player_id) %>%
  mutate(gp_covid = sum(gp),
         championship = ifelse(league %in% c("WC","WJC-18", "WJC-20"), TRUE, FALSE)) %>%
  ungroup() %>%
  select(player_id, gp_covid, championship) %>%
  filter(duplicated(player_id) == FALSE)

# Compute player quality vars using pm
ohl_pm <- ohl %>%
  filter(season %in% c("2019-2020", "2021-2022"), league == "OHL") %>%
  group_by(team_name, season) %>%
  arrange(team_name, season, desc(pm)) %>%
  mutate(pm_rank = 1:n(),
         pm_relative = pm - mean(pm)
  ) %>%
  ungroup() %>%
  select(player_id, team_name, season, pm_rank, pm_relative)

# We need to check that each player played in the OHL in 2019-2020 and 2021-2022
ohl_szn <- ohl %>%
  filter(season %in% c("2019-2020", "2021-2022"), league == "OHL") %>%
  group_by(player_id) %>%
  mutate(played_2019 = season == "2019-2020",
         played_2021 = season == "2021-2022",
         played_both_szn = sum(played_2019) & sum(played_2021)) %>%
  ungroup() %>%
  filter(played_both_szn == TRUE)

# Add treatment vars and pm
ohl_treatment <- ohl_szn %>%
  left_join(ohl_treatment_prep, by = "player_id") %>%
  left_join(ohl_pm, by = c("player_id", "team_name", "season"))

# add treatment variable through join
# ohl_trt <- ohl_szn %>%
#   left_join(select(ohl_treatment, player_id, season, team_name, treatment), by = c("player_id", "team_name", "season")) %>%
#   mutate(ppg = pts/gp) 

# add age variable
ohl_age <- ohl_treatment %>%
  group_by(player_id, season) %>%
  mutate(year = strsplit(season, "-")[[1]][1]) %>%
  mutate(age = trunc((dob %--% as.Date(paste0(year, "-9-15"))) / years(1)),
         age_continuous = (dob %--% as.Date(paste0(year, "-09-15"))) / years(1)
  ) %>%
  ungroup()
    
# add player performance
# ohl_performance <- ohl_age %>%
#   group_by(player_id, season) %>%
#   mutate(ppg_total = sum(pts)/sum(gp),
#          gp_total = sum(gp),
#          pts_total = sum(pts)
#          ) %>%
#   arrange(player_id, season, -plyr_quality) %>%
#   filter(duplicated(player_id) == FALSE) %>%
#   ungroup()

# summarizing variables, adding player performance as ppg
ohl_performance <- ohl_age %>%
  group_by(player_id, season) %>%
  mutate(ppg_total = sum(pts)/sum(gp),
         gp_total = sum(gp),
         pts_total = sum(pts),
         pm_relative = mean(pm_relative),
         pm_rank = trunc(mean(pm_rank)),
  ) %>%
  arrange(player_id, season) %>%
  filter(duplicated(player_id) == FALSE) %>%
  ungroup()

# were they drafted?
ohl_filtered <- ohl_performance %>%
  mutate(drafted = !is.na(draft_year)) 

# clean up
ohl_filtered <- ohl_filtered %>%
  replace_na(list(gp_covid = 0, championship = FALSE)) %>%
  select(season, player_id, championship, gp_covid, first_name, last_name, position, age, gp_total, pts_total, ppg_total, drafted, draft_year, round, overall_pick_num, age_continuous, pm_relative, pm_rank, pm)

# just 2021-2022 season
ohl_treatment_21_22 <- ohl_filtered %>%
  filter(season == "2021-2022")
```

### Modeling

```{r}
ohl_filtered <- ohl_filtered %>%
  mutate(ppg_alt = ppg_total + .001)
ohl_glm_interaction <- glm(ppg_alt ~ position*pm_relative + gp_covid*drafted + drafted*season + gp_total + pm_relative*gp_total + pm_relative*drafted + age_continuous*pm_relative + season + championship, 
                          data = ohl_filtered, 
                          family = Gamma(log))
plot(ohl_glm_interaction, which = 1)
summary(ohl_glm_interaction)
```



...

